# docker-compose.yml

version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=3000
    volumes:
      - .:/app  # 로컬 파일 시스템을 /app 디렉토리에 마운트
